RailsApp/config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles
  resources :folders do
    resources :tasks
  end

end

RailsApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RailsApp/app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }
  end

RailsApp/app/models/folder.rb
class Folder < ApplicationRecord
    validates :title, presence: true

end

RailsApp/app/models/task.rb
class Task < ApplicationRecord
    validates :title, presence: true, length: { maximum: 100 }
    validates :due_date, presence: true
    validate :date_before_start



  def date_before_start
    return if due_date.blank?
    errors.add(:due_date, "には今日以降の日付を入力してください。") if due_date < Date.today
  end

    # status状態定義
    NOT_STARTED = 1
    IN_START = 2
    COMPLETED = 3

    STATUS = {
        NOT_STARTED => { label: '未着手', class: 'label-danger' },
        IN_START => { label: '着手中', class: 'label-info' },
        COMPLETED => { label: '完了', class:'' },
    }
end

RailsApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RailsApp/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      # showへ遷移
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

RailsApp/app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  def index
  end

  def new
    @folder = Folder.new
  end

  def create
    @folder = Folder.new(article_params)

    if @folder.save
      # showへ遷移
      redirect_to folder_tasks_path(folder_id:@folder.id)
    else
      render :new
    end
  end

  private
  def article_params
    params.require(:folder).permit(:title)
  end
end

RailsApp/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @folders = Folder.all
    @current_folder = Folder.find(params[:folder_id])
    @tasks = Task.where(folder_id: @current_folder.id)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to folder_tasks_path(folder_id: @task.folder_id)
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to folder_tasks_path(folder_id: @task.folder_id)
    else
      render :edit
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :status, :due_date).merge!(:folder_id => params[:folder_id])
  end
end

RailsApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsApp/app/helpers/articles_helper.rb
module ArticlesHelper
end

RailsApp/app/helpers/folders_helper.rb
module FoldersHelper
end

RailsApp/app/helpers/tasks_helper.rb
module TasksHelper
    def status_class(status)
        Task::STATUS[status][:class]
    end

    def status_label(status)
        Task::STATUS[status][:label]
    end

    def status_label_only()
        label_hash = Hash.new
        Task::STATUS.each do |k, v|
            label_hash.merge!(v[:label] => k)
        end

        label_hash
    end

end

RailsApp/app/views/articles/_form.html.erb
<!-- form_withの場合、デフォルト非同期処理となる為、同期的に処理したい場合は「local: true」をつける必要がある-->
<!-- 非同期処理状態だとコントローラー側でrenderをしても反応しない為、意図的に同期的に処理する必要がある-->
<%= form_with model: article, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

RailsApp/app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<!-- @articleをローカル変数としてパーシャルに渡す-->
<!-- _form.html.erbでは「article」が使用できる-->
<%= render "form", article: @article %>

RailsApp/app/views/articles/index.html.erb
<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    <li>
      <%= link_to article.title, article %>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_article_path %>

RailsApp/app/views/articles/new.html.erb
<h1>New Article</h1>

<!-- @articleをローカル変数としてパーシャルに渡す-->
<!-- _form.html.erbでは「article」が使用できる-->
<%= render "form", article: @article %>

RailsApp/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                method: :delete,
                data: { confirm: "Are you sure?" } %></li>
</ul>

RailsApp/app/views/folders/index.html.erb
<h1>Folders#index</h1>
<p>Find me in app/views/folders/index.html.erb</p>

RailsApp/app/views/folders/new.html.erb
<div class="container">
    <div class="row">
    <div class="col col-md-offset-3 col-md-6">
        <nav class="panel panel-default">
        <div class="panel-heading">フォルダを追加する</div>
        <div class="panel-body">
            <%= form_with model: @folder, local: true do |form| %>
            <div class="form-group">
                <%= form.label :title, 'フォルダ名' %><br>
                <%= form.text_field :title, {class: "form-control"} %>
                <% @folder.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
                <% end %>
            </div>
            <div class="text-right">
                <%= form.submit('送信', class: "btn btn-primary") %>
            </div>
            <% end %>
        </div>
        </nav>
    </div>
    </div>
</div>

RailsApp/app/views/layouts/application.html.erb
<html lang="ja">
  <header>
    <nav class="my-navbar">
      <a class="my-navbar-brand" href="/">Rails</a>
    </nav>
  </header>
  <head>
    <title>Rails</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

RailsApp/app/views/tasks/_form.html.erb
<!-- form_withの場合、デフォルト非同期処理となる為、同期的に処理したい場合は「local: true」をつける必要がある-->
<!-- 非同期処理状態だとコントローラー側でrenderをしても反応しない為、意図的に同期的に処理する必要がある-->
<%= form_with model: task, url: task_url, local: true do |form| %>
  <div class="form-group">
      <%= form.label :title, 'タイトル' %><br>
      <%= form.text_field :title, {class: "form-control"} %>
      <% task.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div class="form-group">
      <%= form.label :status, '状態' %><br>
      <%= form.select :status, status_label_only, {selected: 1}, { class: 'form-control' , required: true } %>
      <% task.errors.full_messages_for(:status).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div class="form-group">
      <%= form.label :due_date, '期限' %><br>
      <%= form.text_field :due_date, {id: "flatpickr", class: "form-control", readonly: "", value: task.due_date.nil? ? '' : l(task.due_date, format: :default)} %>
      <% task.errors.full_messages_for(:due_date).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>
  <div class="text-right">
      <%= form.submit('送信', class: "btn btn-primary") %>
  </div>
<% end %>


  <script>
    flatpickr(document.getElementById('due_date'), {
      locale: 'ja',
      dateFormat: "Y/m/d",
      minDate: new Date()
    });
  </script>

RailsApp/app/views/tasks/edit.html.erb
<div class="container">
    <div class="row">
    <div class="col col-md-offset-3 col-md-6">
        <nav class="panel panel-default">
        <div class="panel-heading">タスクを編集する</div>
        <div class="panel-body">
            <!-- @taskをローカル変数としてパーシャルに渡す-->
            <!-- _form.html.erbでは「task」が使用できる-->
            <%= render "form", task: @task, task_url: folder_task_path(folder_id: @task.folder_id, id: @task.id) %>
        </div>
        </nav>
    </div>
    </div>
</div>

RailsApp/app/views/tasks/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col col-md-4">
        <nav class="panel panel-default">
          <div class="panel-heading">フォルダ</div>
          <div class="panel-body">
            <a href="<%= new_folder_path%>" class="btn btn-default btn-block">
              フォルダを追加する
            </a>
          </div>
          <div class="list-group">
            <% @folders.each do |folder| %>
              <%= link_to folder.title, folder_tasks_path(folder), {class: "list-group-item #{ @current_folder.id == folder.id ? 'active' : '' }"} %>
            <% end %>
          </div>
        </nav>
      </div>
      <div class="column col-md-8">
        <div class="panel panel-default">
          <div class="panel-heading">タスク</div>
          <div class="panel-body">
              <div class="text-right">
              <a href="<%= new_folder_task_path%>" class="btn btn-default btn-block">
                  タスクを追加する
              </a>
              </div>
          </div>
          <table class="table">
              <thead>
              <tr>
              <th>タイトル</th>
              <th>状態</th>
              <th>期限</th>
              <th></th>
              </tr>
              </thead>
              <tbody>
                <% @tasks.each do |task| %>
                  <tr>
                  <td><%= task.title %></td>
                  <td><span class="label <%= status_class(task.status) %>"><%= status_label(task.status) %></span></td>
                  <td><%= l(task.due_date, format: :default) %></td>
                  <td><a href="<%= edit_folder_task_path(folder_id: task.folder_id, id: task.id)%>">編集</a></td>
                  </tr>
                <% end %>
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</main>

RailsApp/app/views/tasks/new.html.erb
<div class="container">
    <div class="row">
    <div class="col col-md-offset-3 col-md-6">
        <nav class="panel panel-default">
        <div class="panel-heading">タスクを追加する</div>
        <div class="panel-body">
            <!-- @taskをローカル変数としてパーシャルに渡す-->
            <!-- _form.html.erbでは「task」が使用できる-->
            <%= render "form", task: @task, task_url: {controller: 'tasks', action: 'create'} %>
        </div>
        </nav>
    </div>
    </div>
</div>